package br.com.app.conatus.commons.enums;

public enum CodigoDominio {
	
	STATUS_ATIVO,
	CARGO_PROPRIETARIO, 
	MOVIM_CONTRATACAO_MODULO, 
	MOVIM_ATIVACAO_FUNC_PREMIUM, 
	FUNC_PADRAO,
	MOVIM_ATIVACAO_AMOSTRA_GRATIS

}
